### PR TITLE
fix-object-properties

### PR DESCRIPTION
**Pull request by Titozzz**
Following #86, I've noticed that replacing object properties should also be prevented to avoid issues.

Before, this would crash:
```tsx
const test = {};
test.__DEV__; // with __DEV__: false
```

### CODE REVIEW

**Review by gksander — APPROVED** [review]
This looks good! Thanks for the nudge, I must not have seen this one come through!

**Comment by gksander** [comment]
@Titozzz will you add a patch changeset record to this with `yarn changeset` and push that up? With that in place, we can get this merged and released ASAP!

**Comment by Titozzz** [comment]
@gksander All good, sorry for the delay!

**Review by gksander — APPROVED** [review]

**Comment by gksander** [comment]
Thanks once again @Titozzz! This change has been released as version 2.1.4.

**Pull request merged**
