### PR TITLE
Fix vulnerabilities found via npm audit

### PR DESCRIPTION
**Pull request by GaxZE**
## Issue
Found the following when running `npm install`
```sh
added 504 packages from 282 contributors, updated 11 packages and audited 4150 packages in 10.457s
found 189 vulnerabilities (188 low, 1 critical)
  run `npm audit fix` to fix them, or `npm audit` for details
```

## What I've done
I've updated package.json to secure the packages.

## How to test
run `npm test`

```sh
  babel-plugin-transform-define
    transformation tests
      ✓ should transform Unary Expressions
      ✓ should transform Identifiers
      ✓ should transform false
      ✓ should transform 0
      ✓ should transform empty string
      ✓ should transform null
      ✓ should transform undefined
      ✓ should transform code from config in a file
      Member Expressions
        ✓ should transform with config defined by String keys
        ✓ should transform with config defined by an Object
    unit tests
      getSortedObjectPaths
        ✓ should return an array
        ✓ should return a complete list of paths
        ✓ should return a list sorted by length


  13 passing (253ms)
```

## Result
```sh
npm audit

                       === npm audit security report ===

found 0 vulnerabilities
 in 4143 scanned packages
```

### CODE REVIEW

**Comment by GaxZE** [comment]
@boygirl as you closed #51 can you take a look at this?

**Comment by simonstaton** [comment]
Possible to get this merged in? This package is now failing npm audits due to lodash

**Comment by pdf13** [comment]
Let's get this merged! 🚀

**Comment by HofmannZ** [comment]
LGTM

**Comment by lvnilesh** [comment]
Appreciate if you can please merge. Thanks.

**Comment by GaxZE** [comment]
New years resolution?!

**Comment by boygirl** [comment]
Sorry for the delay!

**Pull request merged**
